In [101]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [102]:
with open(r"C:\Users\bhoik\OneDrive\Desktop\Transformer-Neural-Network-main\A_my files\hindi_10000.txt","r") as f:
    hindi_sen = f.readlines()


In [103]:
hindi_sen[:5]

['आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था।\n',
 'और जो शख्स (अपने आमाल का) बदला दुनिया ही में चाहता है तो ख़ुदा के पास दुनिया व आख़िरत दोनों का अज्र मौजूद है और ख़ुदा तो हर शख्स की सुनता और सबको देखता है\n',
 'जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि प्रजातियों की समृद्धि के मामले में उनकी संख्या अन्य जीव समूहों से ज़्यादा है।\n',
 'आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को\n',
 '8 सितम्\u200dबर, 2016 को माननीय राष्\u200dट्रपति की स्\u200dवीकृति मिलने के बाद 101वां संविधान संशोधन अधिनियम, 2016 अस्तित्\u200dव में आया\n']

In [104]:
word_hind = "".join(hindi_sen)


In [105]:
word_hind[:1000]

'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था।\nऔर जो शख्स (अपने आमाल का) बदला दुनिया ही में चाहता है तो ख़ुदा के पास दुनिया व आख़िरत दोनों का अज्र मौजूद है और ख़ुदा तो हर शख्स की सुनता और सबको देखता है\nजैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि प्रजातियों की समृद्धि के मामले में उनकी संख्या अन्य जीव समूहों से ज़्यादा है।\nआस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को\n8 सितम्\u200dबर, 2016 को माननीय राष्\u200dट्रपति की स्\u200dवीकृति मिलने के बाद 101वां संविधान संशोधन अधिनियम, 2016 अस्तित्\u200dव में आया\nअदालत ने इस मामले में आगे की सुनवाई के लिए एक फरवरी की तारीख़ तय की\nजहाँ पर ट्रैक को विभाजित किया जाना है, कृपया वह स्थान चुनें.\nइसके तुरंत बाद सेना की 22 राष्ट्रीय राइफल्स (आरआर), सीआरपीएफ और पुलिस के स्पेशल ऑपरेशन ग्रुप (एसओजी) के जवानों द्वारा इलाके की घेराबंदी कर तलाशी अभियान चलाया।\nझारखंड के मुख्यमंत्री हेमंत सोरेन (फोटोः पीटीआई)\nसेक्टर 55/56 के एसएचओ अरविंद कुमार ने बत

In [106]:
hindi_vocab = sorted(set(word_hind))

In [107]:
print(hindi_vocab)
len(hindi_vocab)

['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '~', '\xa0', '¡', '¨', '©', 'ª', '°', '²', '¶', '»', 'Â', 'Ó', '×', 'æ', 'í', 'ï', 'ə', 'ˌ', 'ː', 'χ', 'آ', 'ا', 'ب', 'ة', 'ت', 'ر', 'ش', 'ط', 'ق', 'ك', 'ل', 'م', 'ن', 'ي', 'پ', 'ँ', 'ं', 'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ऎ', 'ए', 'ऐ', 'ऑ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'ङ', 'च', 'छ', 'ज', 'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ऱ', 'ल', 'व', 'श', 'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'ॅ', 'ॆ', 'े', 'ै', 'ॉ', 'ॊ', 'ो', 'ौ', '्', 'क़', 'ख़', 'ग़', 'ज़', 'ड़', 'ढ़', 'फ़', 'य़', '।',

231

In [108]:
with open(r"C:\Users\bhoik\OneDrive\Desktop\Transformer-Neural-Network-main\A_my files\english_10000.txt","r") as f:
    english_sen = f.readlines()

In [109]:
len(english_sen)

10000

In [110]:
word_eng = "".join(english_sen)

In [111]:
len(word_eng)

986002

In [112]:
english_vocab = sorted(set(word_eng))

In [113]:
print(english_vocab)
len(english_vocab)

['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}']


93

In [114]:
START_TOKEN = '<START>'
PADDING_TOKEN = '<PADDING>'
END_TOKEN = '<END>'

In [115]:
hindi_vocab.insert(0,START_TOKEN)

In [116]:
len(hindi_vocab)

232

In [117]:
print(hindi_vocab)

['<START>', '\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '~', '\xa0', '¡', '¨', '©', 'ª', '°', '²', '¶', '»', 'Â', 'Ó', '×', 'æ', 'í', 'ï', 'ə', 'ˌ', 'ː', 'χ', 'آ', 'ا', 'ب', 'ة', 'ت', 'ر', 'ش', 'ط', 'ق', 'ك', 'ل', 'م', 'ن', 'ي', 'پ', 'ँ', 'ं', 'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ऎ', 'ए', 'ऐ', 'ऑ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'ङ', 'च', 'छ', 'ज', 'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ऱ', 'ल', 'व', 'श', 'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'ॅ', 'ॆ', 'े', 'ै', 'ॉ', 'ॊ', 'ो', 'ौ', '्', 'क़', 'ख़', 'ग़', 'ज़', 'ड़', 'ढ़', 'फ़'

In [118]:
hindi_vocab.append(PADDING_TOKEN)
hindi_vocab.append(END_TOKEN)

In [119]:
len(hindi_vocab)

234

In [120]:
english_vocab.insert(0,START_TOKEN)
english_vocab.append(PADDING_TOKEN)
english_vocab.append(END_TOKEN)

In [121]:
len(english_vocab)

96

In [122]:
hindi_to_index = {k:v for v,k in enumerate(hindi_vocab)}
index_to_hindi = {k:v for k,v in enumerate(hindi_vocab)}
english_to_index = {k:v for v,k in enumerate(english_vocab)}
index_to_english = {k:v for k,v in enumerate(english_vocab)}

In [123]:
hoe = [english_to_index[char] for char in list('hello')]

In [124]:
def encoder(sentence,vocab):
    vector  = [vocab[char] for char in list(sentence)]
    return vector

def decoder(vector,vocab):
    string = "".join([vocab[token] for token in vector])
    return string

In [125]:
encoder("kalpesh",english_to_index)

[75, 65, 76, 80, 69, 83, 72]

In [126]:
decoder([75, 65, 76, 80, 69, 83, 72],index_to_english)

'kalpesh'

In [127]:
encoder("कॉरपोरेट",hindi_to_index)

[140, 186, 167, 161, 188, 167, 184, 150]

In [128]:
decoder([140, 186, 167, 161, 188, 167, 184, 150],index_to_hindi)

'कॉरपोरेट'

In [129]:
max(len(sen) for sen in hindi_sen), max(len(sen) for sen in english_sen)

(3271, 1349)

In [130]:
dict = {key: len(sen) for key,sen in enumerate(english_sen)}

In [131]:
# for i,j in dict.items():
#     if j ==1349:
#         print(i)

In [132]:
hindi_sen[7750]

'कॉरपोरेट कार्य मंत्रालय सीसीआई ने के.रहेजा कॉर्प ग्रुप द्वारा माइंडस्पेस रीट की स्थापना से संबंधित संयोजन को मंजूरी दी भारतीय प्रतिस्पर्धा आयोग (सीसीआई) ने प्रतिस्पर्धा अधिनियम, 2002 की धारा 31(1) के तहत के.रहेजा कॉर्प ग्रुप द्वारा माइंडस्पेस रीट की स्थापना करने और रीट द्वारा लक्षित निकायों में हिस्सेदारी बेचने वाले शेयरधारकों की विशिष्ट इक्विटी अंशभागिता के अधिग्रहण से संबंधित प्रस्तावित संयोजन को मंजूरी दे दी है। इस संयोजन के पक्षकार निम्नलिखित हैं : अधिग्रहणकर्ता : माइंडस्पेस बिजनेस पार्क्स रीट (माइंडस्पेस रीट) लक्षित निकाय : के.रहेजा आईटी पार्क (हैदराबाद) लिमिटेड, इनटाइम प्रॉपर्टीज लिमिटेड, सनड्यू प्रॉपर्टीज लिमिटेड, एवाकैडो प्रॉपर्टीज एंड ट्रेडिंग (इंडिया) प्राइवेट लिमिटेड, गीगाप्लेक्स एस्टेट प्राइवेट लिमिटेड, केआरसी इन्फ्रास्ट्रक्चर एंड प्रोजेक्ट्स प्राइवेट लिमिटेड, होराइजनव्यू प्रॉपर्टीज प्राइवेट लिमिटेड और माइंडस्पेस बिजनेस पार्क्स प्राइवेट लिमिटेड माइंडस्पेस रीट की स्थापना भारतीय ट्रस्ट अधिनियम,1882 के प्रावधानों के तहत एक अंशदायी, अपरिवर्तनीय और सुव्यवस्थित ट्रस्ट के रूप में

In [133]:
import numpy as np

In [134]:
per = 93
print(f"{per} percent of hindi sentence has average len of: {np.percentile([len(word) for word in hindi_sen],per)}")
print(f"{per} percent of english sentence has average len of: {np.percentile([len(word) for word in english_sen],per)}")

93 percent of hindi sentence has average len of: 201.0699999999997
93 percent of english sentence has average len of: 214.0699999999997


In [135]:
max_seq_len = 200

def valid_len_sentence(sentence,max_seq_len):
    return len(list(sentence)) < (max_seq_len-1)

def valid_sentence_token(sentence,vocab):
    for token in list(set(sentence)):
        if token not in vocab:
            return False
    return True

valid_index = []

for index in range(len(hindi_sen)):
    hindi_sentence, english_sentence = hindi_sen[index], english_sen[index]
    if valid_len_sentence(hindi_sentence,max_seq_len) and valid_len_sentence(english_sentence,max_seq_len) \
    and valid_sentence_token(hindi_sentence,hindi_vocab):
        valid_index.append(index)

In [136]:
len(hindi_sen), len(valid_index)

(10000, 8913)

In [137]:
valid_index[8090]

9074

In [138]:
hindi_sentence = [hindi_sen[i] for i in valid_index]
english_sentence =  [english_sen[i] for i in valid_index]

In [139]:
len(hindi_sentence), len(english_sentence)

(8913, 8913)

In [140]:
max(len(sen) for sen in hindi_sentence),max(len(sen) for sen in english_sentence )

(198, 198)

In [141]:
from torch.utils.data import Dataset, DataLoader

class TextDataSet(Dataset):

    def __init__(self, english_sentence , hindi_sentence):
        self.english_sentence = english_sentence
        self.hindi_sentence = hindi_sentence


    def __len__(self):
        return len(self.english_sentence)
    
    def __getitem__(self, idx) :
        return self.english_sentence[idx] , self.hindi_sentence[idx]


In [142]:
dataset = TextDataSet(english_sentence,hindi_sentence)

In [143]:
len(dataset)

8913

In [144]:
dataset[1]

('Whosoever desires the reward of the world, with Allah is the reward of the world and of the Everlasting Life. Allah is the Hearer, the Seer.\n',
 'और जो शख्स (अपने आमाल का) बदला दुनिया ही में चाहता है तो ख़ुदा के पास दुनिया व आख़िरत दोनों का अज्र मौजूद है और ख़ुदा तो हर शख्स की सुनता और सबको देखता है\n')

In [145]:
batchSize = 3
train_data_loader = DataLoader(dataset,batchSize)
iterator = iter(train_data_loader)

In [146]:
for i,sen in enumerate(iterator):
    if i == 5:
        break
    print(sen)


[("However, Paes, who was partnering Australia's Paul Hanley, could only go as far as the quarterfinals where they lost to Bhupathi and Knowles\n", 'Whosoever desires the reward of the world, with Allah is the reward of the world and of the Everlasting Life. Allah is the Hearer, the Seer.\n', 'The value of insects in the biosphere is enormous because they outnumber all other living groups in measure of species richness.\n'), ('आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था।\n', 'और जो शख्स (अपने आमाल का) बदला दुनिया ही में चाहता है तो ख़ुदा के पास दुनिया व आख़िरत दोनों का अज्र मौजूद है और ख़ुदा तो हर शख्स की सुनता और सबको देखता है\n', 'जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि प्रजातियों की समृद्धि के मामले में उनकी संख्या अन्य जीव समूहों से ज़्यादा है।\n')]
[('Mithali To Anchor Indian Team Against Australia in ODIs\n', 'After the assent of the Honble President on 8thSeptember, 2016, 

In [147]:
def tokenization(sentence,lang_to_index,start_token=True,end_token=True):
    token = encoder(sentence,lang_to_index)
    if start_token:
        token.insert(0,lang_to_index[START_TOKEN])
    if end_token:
        token.append(lang_to_index[END_TOKEN])
    for _ in range(len(token),max_seq_len):
        token.append(lang_to_index[PADDING_TOKEN])
    return torch.tensor(token)

In [148]:
token = tokenization(hindi_sentence[3],hindi_to_index)

In [149]:
len(token),token[:10]

(200, tensor([  0, 128, 173, 190, 150, 190, 167, 184, 169, 177]))

In [150]:
len(dataset[0:][0]), dataset[0][0] # all enghish sentences in dataset

(8913,
 "However, Paes, who was partnering Australia's Paul Hanley, could only go as far as the quarterfinals where they lost to Bhupathi and Knowles\n")

In [151]:
len(dataset[:][1]),dataset[0][1] # all hindi sentences in dataset

(8913,
 'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था।\n')

In [152]:
eng_token,hin_token = [],[]
for idx,batch_sentence in enumerate(train_data_loader):
    if idx == 5:
        break
    for sentence_num in range(len(batch_sentence[0])):
        eng , hindi = batch_sentence[0][sentence_num] , batch_sentence[1][sentence_num]
        eng_token.append(tokenization(eng,english_to_index,start_token=False,end_token=False))
        hin_token.append(tokenization(hindi,hindi_to_index))
    
   
eng_token = torch.stack((eng_token))
hin_token = torch.stack(hin_token)
        

In [153]:
len(eng_token[0]),eng_token[:]

(200,
 tensor([[41, 79, 87,  ..., 94, 94, 94],
         [56, 72, 79,  ..., 94, 94, 94],
         [53, 72, 69,  ..., 94, 94, 94],
         ...,
         [52, 69, 78,  ..., 94, 94, 94],
         [46, 69, 65,  ..., 94, 94, 94],
         [44, 65, 84,  ..., 94, 94, 94]]))

In [154]:
len(hin_token[0]),hin_token[:]

(200,
 tensor([[  0, 128, 173,  ..., 232, 232, 232],
         [  0, 139, 167,  ..., 232, 232, 232],
         [  0, 147, 185,  ..., 232, 232, 232],
         ...,
         [  0, 173, 164,  ..., 232, 232, 232],
         [  0, 129, 173,  ..., 232, 232, 232],
         [  0, 140, 150,  ..., 232, 232, 232]]))

In [155]:
ahed = torch.full([10,10],True)
print(ahed)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])


In [156]:
ahed = torch.triu(ahed,diagonal=1)
ahed


tensor([[False,  True,  True,  True,  True,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True,  True,  True,  True,  True],
        [False, False, False,  True,  True,  True,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False, False, False, False,  True],
        [False, False, False, False, False, False, False, False, False, False]])

In [157]:
look = torch.full([4,4],True)
look = torch.triu(look,diagonal=1)

dec = torch.tensor([[[True,False,False,True],
                    [False,False,False,True],
                    [False,False,False,True],
                    [False,False,False,True]],
                    [[False, False, False,  True],
        [False, False, False,  True],
        [False, False, False,  True],
        [False, False, False,  True]]])

In [158]:
dec,look

(tensor([[[ True, False, False,  True],
          [False, False, False,  True],
          [False, False, False,  True],
          [False, False, False,  True]],
 
         [[False, False, False,  True],
          [False, False, False,  True],
          [False, False, False,  True],
          [False, False, False,  True]]]),
 tensor([[False,  True,  True,  True],
         [False, False,  True,  True],
         [False, False, False,  True],
         [False, False, False, False]]))

In [159]:
new = look+dec
new

tensor([[[ True,  True,  True,  True],
         [False, False,  True,  True],
         [False, False, False,  True],
         [False, False, False,  True]],

        [[False,  True,  True,  True],
         [False, False,  True,  True],
         [False, False, False,  True],
         [False, False, False,  True]]])

In [160]:
def MaskCreation(english_batch,hindi_batch):
    NEG_INFTY = -1e9
    max_len = 200
    number_sen = len(english_batch)
    english_sen_len , hindi_sen_len = english_batch[0] , hindi_batch[0]
    look_ahed_mask = torch.full([max_len,max_len],True)
    look_ahed_mask = torch.triu(look_ahed_mask,diagonal=1)
    encoder_padding_mask = torch.full([number_sen,max_len,max_len],False)
    decoder_self_padding_mask = torch.full([number_sen,max_len,max_len],False)
    decoder_cross_padding_mask = torch.full([number_sen,max_len,max_len],False)

    for idx in range(sentence_num):
        english_sen_len , hindi_sen_len = len(english_batch[idx]) , len(hindi_batch[idx])
        english_char_padding = np.arange(english_sen_len+1,max_len)
        hindi_char_padding = np.arange(hindi_sen_len+1,max_len)
        encoder_padding_mask[idx,:,english_char_padding]=True
        encoder_padding_mask[idx,english_char_padding,:] = True
        decoder_self_padding_mask[idx,:,hindi_char_padding] = True
        decoder_self_padding_mask[idx,hindi_char_padding,:] = True
        decoder_cross_padding_mask[idx,:,english_char_padding] = True
        decoder_cross_padding_mask[idx,hindi_char_padding,:] = True

    encoder_self_attention_mask = torch.where(encoder_padding_mask,NEG_INFTY,0)
    decoder_self_attention_mask = torch.where(look_ahed_mask+decoder_self_padding_mask,NEG_INFTY,0)
    decoder_cross_attention_mask = torch.where(decoder_cross_padding_mask,NEG_INFTY,0)
    print(f"size fo encoder mask = {encoder_self_attention_mask.size()}\n{encoder_self_attention_mask[0,:1,:100]}")
    print(f"size fo decoder self mask = {decoder_self_attention_mask.size()}\n{decoder_self_attention_mask[0,:10,:15]}")
    print(f"size fo decoder cross mask = {decoder_cross_attention_mask.size()}\n{decoder_cross_attention_mask[0,:1,:100]}")

    return encoder_self_attention_mask ,decoder_self_attention_mask,decoder_cross_attention_mask

    



In [161]:
len(sen[0][0]),len(sen[1][0])

(79, 75)

In [162]:
mask = MaskCreation(sen[0],sen[1])

size fo encoder mask = torch.Size([3, 200, 200])
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0

In [163]:
import torch.nn as nn

In [164]:
class Positional_embeddings(nn.Module):
    def __init__(self,d_model,max_seq_len):
        self.d_model = d_model
        self.max_seq_len = max_seq_len

    def forward(self):
        even_idx = torch.arange(0,self.d_model,2)
        # odd_idx = torch.arange(1,d_model,2)
        denominator = torch.pow(10000,even_idx/self.d_model)
        # print(denominator)
        pos = torch.arange(self.max_seq_len,dtype=torch.float64).reshape(self.max_seq_len,1)
        # print(pos)
        even_pe = torch.sin(pos/denominator)
        # print(even_pe)
        odd_pe = torch.cos(pos/denominator)
        # print(odd_pe)
        stacked = torch.stack([even_pe,odd_pe],dim=2)
        # print(stacked)
        PE = torch.flatten(stacked,start_dim=1,end_dim=2)

        return PE

In [165]:
pe = Positional_embeddings(d_model=512,max_seq_len=200)

In [166]:
pe.forward()

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
          0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  8.2186e-01,  ...,  1.0000e+00,
          1.0366e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  9.3641e-01,  ...,  1.0000e+00,
          2.0733e-04,  1.0000e+00],
        ...,
        [ 7.9581e-01, -6.0555e-01,  9.9961e-01,  ...,  9.9978e-01,
          2.0420e-02,  9.9979e-01],
        [-7.9579e-02, -9.9683e-01,  5.9249e-01,  ...,  9.9977e-01,
          2.0524e-02,  9.9979e-01],
        [-8.8180e-01, -4.7163e-01, -3.2453e-01,  ...,  9.9977e-01,
          2.0628e-02,  9.9979e-01]], dtype=torch.float64)

In [167]:
import torch.nn as nn

In [168]:
class SentenceEmbedding(nn.Module):
    def __init__(self,max_seq_len,d_model,language_to_index,PADDING_TOKEN,START_TOKEN,END_TOKEN):
        super().__init__()
        self.vocab_size = len(language_to_index)
        self.max_seq_len = max_seq_len
        self.d_model = d_model
        self.language_to_index = language_to_index
        self.PADDING_TOKEN = PADDING_TOKEN
        self.START_TOKEN = START_TOKEN
        self.END_TOKEN = END_TOKEN
        self.embeddings = nn.Embedding(self.vocab_size,self.d_model)
        self.positon_encoding = Positional_embeddings(self.d_model,self.max_seq_len) # type: ignore
        self.dropout = nn.Dropout(0.1)

    def batch_token(self,batch,start_token=True,end_token=True):
        def tokenizer(sentence,start_token=True,end_token=True):
            sentence_to_token = [self.language_to_index[token] for token in list(sentence)]
            if start_token:
                sentence_to_token.insert(0,self.language_to_index[self.START_TOKEN])
            if end_token:
                sentence_to_token.append(self.language_to_index[self.END_TOKEN])
            for _ in range((len(sentence_to_token)),self.max_seq_len):
                sentence_to_token.append(self.language_to_index[self.PADDING_TOKEN])
            return torch.tensor(sentence_to_token)
        
        tokens=[]

        for i in range(len(batch)):
            tokens.append(tokenizer(batch[i],start_token,end_token))
        tokens = torch.stack(tokens)
        return tokens

    def forward(self,btc,start_token = True):
        x = self.batch_token(btc)
        # print(x.shape)
        x = self.embeddings(x)
        # print(x.shape)
        pos = self.positon_encoding.forward()
        # print(pos.shape)
        x = self.dropout(x+pos)
        return x

        

In [169]:
Emb_sen = SentenceEmbedding(max_seq_len=200,
                            d_model=512,
                            language_to_index=hindi_to_index,
                            PADDING_TOKEN=PADDING_TOKEN,
                            START_TOKEN=START_TOKEN,
                            END_TOKEN=END_TOKEN)

In [170]:
sen[1]

('वह ऐसा इसलिए करता है, क्योंकि वह भारतीय तिरंगे के कथित अनादर से क्रोधित है\n',
 'रंधावा से एक हफ्ते से उनके मोबाईल पर सम्पर्क करने की कोशिश की गयी, लेकिन बात नहीं हो पायी।\n',
 'नैनो की तुलना में अल्टो 800 का डिज़ाइन वेवफ्रंट है जो पारंपरिक कार की तरह दिखता है।\n')

In [171]:
self_obj = Emb_sen.forward(btc=sen[1])

In [172]:
self_obj

tensor([[[ 0.8377,  2.2172,  1.2248,  ...,  2.9184, -0.8868,  2.0046],
         [ 0.4725,  1.7880,  0.3720,  ...,  0.8701,  0.1268,  1.0720],
         [ 1.7007,  1.0310,  0.4041,  ...,  1.5898, -0.0000,  0.6939],
         ...,
         [ 0.8994, -1.7061,  1.6693,  ...,  2.2401, -0.4364, -0.0000],
         [-0.0732, -2.1409,  0.0000,  ...,  2.2401, -0.4362, -1.0666],
         [-0.9646, -1.5573,  0.1980,  ...,  2.2401, -0.4361, -1.0666]],

        [[ 0.8377,  2.2172,  1.2248,  ...,  2.9184, -0.8868,  0.0000],
         [ 0.7482, -0.2052,  1.5270,  ..., -0.3135,  0.0000,  0.4252],
         [ 0.7723, -0.1587, -0.9296,  ..., -0.3659, -1.8049, -0.5281],
         ...,
         [ 0.8994, -1.7061,  1.6693,  ...,  2.2401, -0.0000, -1.0666],
         [-0.0732, -2.1409,  1.2169,  ...,  2.2401, -0.4362, -0.0000],
         [-0.9646, -1.5573,  0.0000,  ...,  2.2401, -0.4361, -0.0000]],

        [[ 0.8377,  2.2172,  1.2248,  ...,  2.9184, -0.8868,  0.0000],
         [ 0.2484, -0.3307,  1.7488,  ...,  1

In [173]:
self_obj.shape

torch.Size([3, 200, 512])